### ISSUE TITLE
Add screenshots for first login to Dev spaces

### ISSUE THREAD

**Issue by ozangunalp** [cescoffier/quarkus-openshift-workshop#132]
After 
> Once in the hero-service component home page, you can launch the Dev Spaces opening by clicking the link OpenShift Dev Spaces (VS Code)

![Screenshot 2024-09-17 at 14 12 55](https://github.com/user-attachments/assets/6f4dc491-bff8-4761-be69-062b0156ed01)
![Screenshot 2024-09-17 at 14 12 46](https://github.com/user-attachments/assets/2d711a59-5ea4-4493-9cbe-cd8baaa7e82a)
![Screenshot 2024-09-17 at 14 12 32](https://github.com/user-attachments/assets/92e30927-92eb-4251-95a2-d2213f5dc832)
![Screenshot 2024-09-17 at 14 12 13](https://github.com/user-attachments/assets/f4cb6a66-0680-48ac-a3b5-85f8932161f1)

**Comment by jponge** [comment]
I think this was completed 😉
